app = "greek-nt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DJANGO_ALLOWED_HOSTS = "gnt.mikebrinker.net,www.gnt.mikebrinker.net,greek-nt.fly.dev,localhost,0.0.0.0"
  ENVIRONMENT = "production"
  DATABASE_CONFIG = "production"
  CSRF_TRUSTED_ORIGINS = "https://greek-nt.fly.dev,https://gnt.mikebrinker.net,https://www.gnt.mikebrinker.net"
  # Database credentials are set as secrets

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/opt/greek-nt/src/staticfiles"
  url_prefix = "/static"

[mounts]
  source = "greek_nt_data"
  destination = "/data"


