app = "greek-nt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DJANGO_ALLOWED_HOSTS = ".fly.dev,localhost,0.0.0.0"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/opt/greek-nt/src/staticfiles"
  url_prefix = "/static"
