"""
Django settings for greek_nt project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file with override to ensure latest values
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c40@%2cl+u#b-62#4_d)x*@mi#+(u-_er9_i(00unpp(si=0_6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Update ALLOWED_HOSTS setting
ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "gnt.mikebrinker.net,www.gnt.mikebrinker.net,greek-nt.fly.dev,localhost,0.0.0.0",
).split(",")
CSRF_TRUSTED_ORIGINS = [
    "https://greek-nt.fly.dev",
    "https://gnt.mikebrinker.net",
    "https://www.gnt.mikebrinker.net",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "greek_nt",
    "tailwind",
    "theme",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "greek_nt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "greek_nt.wsgi.application"


# Database configurations
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Define all database configurations
DATABASES = {
    # Local SQLite database
    "sqlite": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

# Only try to parse DATABASE_URL if it's actually set
# This prevents errors during collectstatic in the Dockerfile build process
if os.getenv("DATABASE_URL"):
    try:
        db_from_url = dj_database_url.parse(os.getenv("DATABASE_URL"), conn_max_age=600)
        
        # Core PostgreSQL connection options
        postgres_options = {
            "sslmode": "require",
            "gssencmode": "disable",
            "options": "-c search_path=public -c pool_mode=transaction"
        }
        
        DATABASES["remote"] = {
            **db_from_url,
            "OPTIONS": postgres_options,
            # Connection pooling - reuse connections for better performance
            "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        }
        
        DATABASES["production"] = {
            **db_from_url,
            "OPTIONS": postgres_options,
            # Connection pooling - reuse connections for better performance
            "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        }
    except ValueError:
        # If DATABASE_URL couldn't be parsed, create fallback entries for remote and production
        # This ensures the settings module can still be loaded even without DATABASE_URL 
        DATABASES["remote"] = DATABASES["sqlite"].copy()
        DATABASES["production"] = DATABASES["sqlite"].copy()

# DATABASE_CONFIG from .env overrides the environment-based default
# This allows specifying any database configuration regardless of environment
DATABASE_CONFIG = os.getenv("DATABASE_CONFIG")

# If DATABASE_CONFIG wasn't explicitly set in .env, use environment-based default
if not DATABASE_CONFIG:
    if ENVIRONMENT == "production":
        DATABASE_CONFIG = "production"
    else:
        DATABASE_CONFIG = "sqlite"

# If the specified configuration doesn't exist, fall back to sqlite
if DATABASE_CONFIG not in DATABASES:
    DATABASE_CONFIG = "sqlite"

# Set the active database configuration
DATABASES["default"] = DATABASES[DATABASE_CONFIG]

# Cache configuration
# Use more aggressive caching in production
if ENVIRONMENT == "production":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "greek_nt_cache",
            "TIMEOUT": 86400,  # 24 hours
            "OPTIONS": {
                "MAX_ENTRIES": 5000,  # Store more items in cache
                "CULL_FREQUENCY": 3,  # Cull 1/3 of entries when MAX_ENTRIES is reached
            },
        }
    }
    
    # Cache key settings
    CACHE_MIDDLEWARE_ALIAS = "default"
    CACHE_MIDDLEWARE_SECONDS = 86400  # 24 hours
    CACHE_MIDDLEWARE_KEY_PREFIX = "greek_nt"
    
    # Enable per-site cache for production
    # This will cache entire pages for anonymous users
    if "django.middleware.cache.UpdateCacheMiddleware" not in MIDDLEWARE:
        # Add caching middleware - insert at the right positions
        MIDDLEWARE.insert(0, "django.middleware.cache.UpdateCacheMiddleware")
        MIDDLEWARE.append("django.middleware.cache.FetchFromCacheMiddleware")
else:
    # Development - minimal caching
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TAILWIND_APP_NAME = "theme"

# For Fly.io Hosting
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "theme" / "static",
]
