# Generated by Django 5.1.5 on 2025-01-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("ref", models.CharField(max_length=20)),
                ("role", models.CharField(blank=True, max_length=1)),
                (
                    "class_field",
                    models.CharField(blank=True, db_column="class", max_length=20),
                ),
                ("type", models.CharField(blank=True, max_length=20)),
                ("english", models.CharField(blank=True, max_length=50)),
                ("mandarin", models.CharField(blank=True, max_length=50)),
                ("gloss", models.CharField(blank=True, max_length=100)),
                ("text", models.CharField(max_length=50)),
                ("after", models.CharField(blank=True, max_length=5)),
                ("lemma", models.CharField(max_length=50)),
                ("normalized", models.CharField(max_length=50)),
                ("strong", models.CharField(max_length=10)),
                ("morph", models.CharField(max_length=20)),
                ("person", models.CharField(blank=True, max_length=10)),
                ("number", models.CharField(blank=True, max_length=10)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("case", models.CharField(blank=True, max_length=20)),
                ("tense", models.CharField(blank=True, max_length=20)),
                ("voice", models.CharField(blank=True, max_length=20)),
                ("mood", models.CharField(blank=True, max_length=20)),
                ("degree", models.CharField(blank=True, max_length=20)),
                ("domain", models.CharField(blank=True, max_length=20)),
                ("ln", models.CharField(blank=True, max_length=20)),
                ("frame", models.CharField(blank=True, max_length=100)),
                ("subjref", models.CharField(blank=True, max_length=100)),
                ("referent", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "token",
                "indexes": [
                    models.Index(fields=["ref"], name="token_ref_e2a68c_idx"),
                    models.Index(fields=["lemma"], name="token_lemma_da9252_idx"),
                    models.Index(fields=["strong"], name="token_strong_af80f0_idx"),
                ],
            },
        ),
    ]
