# Generated by Django 5.1.5 on 2025-02-27 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.CharField(max_length=255)),
                ("result_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "search_events",
                "indexes": [
                    models.Index(
                        fields=["query_text"], name="search_even_query_t_9a57cc_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="search_even_timesta_8d116f_idx"
                    ),
                ],
            },
        ),
    ]
