# Generated by Django 5.1.5 on 2025-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="role",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["text"], name="token_text_be6a67_idx"),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["id"], name="token_id_prefix_idx"),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["text", "lemma", "english", "strong"], name="token_search_idx"
            ),
        ),
    ]
