# Generated by Django 5.1.5 on 2025-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0002_load_sblgnt_token_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["text"], name="token_text_be6a67_idx"),
        ),
    ]
