# Generated by Django 5.1.5 on 2025-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0002_searchevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="role",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
