# Generated by Django 5.1.5 on 2025-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0003_alter_token_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="contextual_glosses",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="token",
            name="frame",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="token",
            name="gloss",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="token",
            name="referent",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="token",
            name="semantic_domain",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="token",
            name="sense_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="token",
            name="subjref",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
