# Generated by Django 5.1.5 on 2025-01-17 16:56
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greek_nt", "0003_token_token_text_be6a67_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["text", "lemma", "english", "strong"], name="token_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["id"], name="token_id_prefix_idx"),
        ),
    ]
