# Generated by Django 5.1.5 on 2025-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0004_alter_token_contextual_glosses_alter_token_frame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="case",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="class_field",
            field=models.CharField(blank=True, db_column="class", max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="degree",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="domain",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="ln",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="mood",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="morph",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="ref",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="tense",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="voice",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
