# Generated by Django 5.1.5 on 2025-02-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0005_alter_token_case_alter_token_class_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="after",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
