# Generated by Django 5.1.5 on 2025-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0006_alter_token_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="after",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="token",
            name="case",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="class_field",
            field=models.CharField(blank=True, db_column="class", max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="contextual_glosses",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="token",
            name="degree",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="english",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="frame",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="gloss",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="id",
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="lemma",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="ln",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="mandarin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="mood",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="morph",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="normalized",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="person",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="ref",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="referent",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="role",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="semantic_domain",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="sense_id",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="strong",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="subjref",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="token",
            name="tense",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="voice",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
