# Generated by Django 5.1.5 on 2025-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greek_nt", "0007_alter_token_after_alter_token_case_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="token",
            new_name="token_text_idx",
            old_name="token_text_be6a67_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_ref_idx",
            old_name="token_ref_e2a68c_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_lemma_idx",
            old_name="token_lemma_da9252_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_strong_idx",
            old_name="token_strong_af80f0_idx",
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["english"], name="token_english_idx"),
        ),
    ]
